---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  LiveStreaming CloudFormation template


Parameters:
  ChannelName:
    Type: String

Resources:
  MediaLiveAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ChannelName}-medialive-role
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "medialive.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

      Policies:
        - PolicyName: MediaLive-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - ec2:*
                  - medialive:*
                  - "*"

  MediaLiveChannel:
    Type: AWS::MediaLive::Channel
    Properties:
      ChannelClass: SINGLE_PIPELINE
      Destinations:
        - Id: "vd5hr"
          Settings:
            - Url: !Join ["",["mediastoressl://",!Select ["1", !Split ["//",!GetAtt AudioStreamOrigin.Endpoint]],"/",!Ref ChannelName]]
      EncoderSettings:
        {
                "AudioDescriptions": [
                    {
                        "AudioTypeControl": "FOLLOW_INPUT",
                        "CodecSettings": {
                            "AacSettings": {
                                "Bitrate": 64000,
                                "CodingMode": "CODING_MODE_2_0",
                                "InputType": "NORMAL",
                                "Profile": "HEV1",
                                "RateControlMode": "CBR",
                                "RawFormat": "NONE",
                                "SampleRate": 48000,
                                "Spec": "MPEG4"
                            }
                        },
                        "LanguageCodeControl": "FOLLOW_INPUT",
                        "Name": "audio_uu92x"
                    }
                ],
                "CaptionDescriptions": [],
                "OutputGroups": [
                    {
                        "Name": "MediaStore",
                        "OutputGroupSettings": {
                            "HlsGroupSettings": {
                                "AdMarkers": [],
                                "CaptionLanguageMappings": [],
                                "CaptionLanguageSetting": "OMIT",
                                "ClientCache": "ENABLED",
                                "CodecSpecification": "RFC_4281",
                                "Destination": {
                                    "DestinationRefId": "vd5hr"
                                },
                                "DirectoryStructure": "SINGLE_DIRECTORY",
                                "HlsCdnSettings": {
                                    "HlsMediaStoreSettings": {
                                        "ConnectionRetryInterval": 1,
                                        "FilecacheDuration": 300,
                                        "MediaStoreStorageClass": "TEMPORAL",
                                        "NumRetries": 10,
                                        "RestartDelay": 15
                                    }
                                },
                                "IFrameOnlyPlaylists": "DISABLED",
                                "IndexNSegments": 10,
                                "InputLossAction": "EMIT_OUTPUT",
                                "IvInManifest": "INCLUDE",
                                "IvSource": "FOLLOWS_SEGMENT_NUMBER",
                                "KeepSegments": 21,
                                "ManifestCompression": "NONE",
                                "ManifestDurationFormat": "FLOATING_POINT",
                                "Mode": "LIVE",
                                "OutputSelection": "MANIFESTS_AND_SEGMENTS",
                                "ProgramDateTime": "EXCLUDE",
                                "ProgramDateTimePeriod": 600,
                                "RedundantManifest": "DISABLED",
                                "SegmentLength": 9,
                                "SegmentationMode": "USE_SEGMENT_DURATION",
                                "SegmentsPerSubdirectory": 10000,
                                "StreamInfResolution": "INCLUDE",
                                "TimedMetadataId3Frame": "PRIV",
                                "TimedMetadataId3Period": 10,
                                "TsFileMode": "SEGMENTED_FILES"
                            }
                        },
                        "Outputs": [
                            {
                                "AudioDescriptionNames": [
                                    "audio_uu92x"
                                ],
                                "CaptionDescriptionNames": [],
                                "OutputSettings": {
                                    "HlsOutputSettings": {
                                        "HlsSettings": {
                                            "AudioOnlyHlsSettings": {
                                                "AudioTrackType": "AUDIO_ONLY_VARIANT_STREAM",
                                                "AudioGroupId": "program_audio",
                                                "SegmentType": "AAC"
                                            }
                                        },
                                        "NameModifier": "_1"
                                    }
                                }
                            }
                        ]
                    }
                ],
                "TimecodeConfig": {
                    "Source": "EMBEDDED"
                },
                "VideoDescriptions": []
            }

      InputAttachments:
        - InputAttachmentName: !Sub ${ChannelName}-input1-name
          InputId: !Ref MediaLiveInput
          InputSettings:
            AudioSelectors: []
            CaptionSelectors: []
            DeblockFilter: DISABLED
            DenoiseFilter: DISABLED
            FilterStrength: 1
            InputFilter: AUTO
            SourceEndBehavior: CONTINUE
      InputSpecification:
          Codec: MPEG2
          MaximumBitrate: MAX_10_MBPS
          Resolution: HD
      LogLevel: DISABLED
      Name: !Sub ${ChannelName}
      RoleArn: !GetAtt MediaLiveAccessRole.Arn

  MediaLiveInput:
    Type: AWS::MediaLive::Input
    Properties:
      Destinations:
          - StreamName: 'app1/inst1'
      InputSecurityGroups:
        - !Ref MediaLiveInputSecurityGroup
      Name: !Sub ${ChannelName}-input1
      Type: 'RTMP_PUSH'

  MediaLiveInputSecurityGroup:
    Type: AWS::MediaLive::InputSecurityGroup
    Properties:
      WhitelistRules:
        - Cidr: '0.0.0.0/0'

  AudioStreamOrigin:
    Type: AWS::MediaStore::Container
    Properties:
      AccessLoggingEnabled: false
      ContainerName: !Ref ChannelName
      CorsPolicy: [
          {
            "AllowedHeaders": ["*"],
            "AllowedMethods": ["GET","HEAD"],
            "AllowedOrigins": ["*"],
            "MaxAgeSeconds": 300
          }
      ]
      Policy: !Sub |
        {
        	"Version": "2012-10-17",
        	"Statement": [{
        		"Sid": "MediaStoreHttpsReadAccessOnly",
        		"Action": [ "mediastore:GetObject", "mediastore:DescribeObject" ],
        		"Principal": "*",
        		"Effect": "Allow",
        		"Resource": "arn:aws:mediastore:${AWS::Region}:${AWS::AccountId}:container/${ChannelName}/*",
        		"Condition": {
        			"Bool": { "aws:SecureTransport": "true" }
        		}
        	}]
        }

  AudioStreamingContentDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Select [1, !Split ["//", !GetAtt AudioStreamOrigin.Endpoint]]
          Id: mediastore
          CustomOriginConfig:
            OriginProtocolPolicy: "https-only"
        Enabled: 'true'
        Comment: !Sub "${AWS::StackName} - distribution for audio live streaming"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: mediastore
          ViewerProtocolPolicy: allow-all
          SmoothStreaming: 'false'
          Compress: 'true'
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: 'none'
        PriceClass: PriceClass_All
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
Outputs:
   PlaybackURL:
    Value: !Join ["",["https://",!GetAtt AudioStreamingContentDistribution.DomainName,"/",!Join ["",[!Ref ChannelName,".m3u8"]]]]
   RTMPIngestEndpoint:
     Value:  !Select ["0", !GetAtt MediaLiveInput.Destinations]
